// data.js
const assignments = [
  {
    id: 1,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "Hyatt Regency Pune Kalyani Nagar",
    chain: "Hyatt",
    total: "₹11.5K",
    location: "Pune, Maharashtra",
    eval: "Spa visit + lunch evaluation",
    duration: "4 hr · 5-star",
    tags: ["spa", "wellness", "lunch"],
    pay: "₹2,000",
    reimburse: "₹9,500",
    closes: "Today",
    deadlineTime: "Feb 18, 2025, 6:00 PM",
    closesDays: 0,
    city: "Pune",
    valueScore: 85
  },
  {
    id: 2,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "The Ritz-Carlton Pune",
    chain: "Ritz-Carlton (Marriott)",
    total: "₹9.5K",
    location: "Pune, Maharashtra",
    eval: "Premium lounge + cocktail bar",
    duration: "3 hr · 5-star deluxe",
    tags: ["lounge", "cocktails", "bar"],
    pay: "₹2,000",
    reimburse: "₹7,500",
    closes: "Today",
    deadlineTime: "Feb 18, 2025, 8:00 PM",
    closesDays: 0,
    city: "Pune",
    valueScore: 92
  },
  {
    id: 3,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "JW Marriott Pune",
    chain: "JW Marriott",
    total: "₹25K",
    location: "Pune, Maharashtra",
    eval: "Overnight stay + F&B + Spa",
    duration: "Overnight · 5-star",
    tags: ["overnight", "spa", "F&B", "couples"],
    pay: "₹5,000",
    reimburse: "₹20,000",
    closes: "Tomorrow",
    deadlineTime: "Feb 19, 2025, 12:00 PM",
    closesDays: 1,
    city: "Pune",
    valueScore: 98
  },
  {
    id: 4,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "Marriott Suites Pune",
    chain: "Marriott",
    total: "₹18K",
    location: "Pune, Maharashtra",
    eval: "Business lounge + breakfast",
    duration: "5 hr · 5-star",
    tags: ["lounge", "breakfast", "business"],
    pay: "₹3,000",
    reimburse: "₹15,000",
    closes: "Tomorrow",
    deadlineTime: "Feb 19, 2025, 4:00 PM",
    closesDays: 1,
    city: "Pune",
    valueScore: 89
  },
  {
    id: 5,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "Sheraton Grand Pune",
    chain: "Marriott",
    total: "₹14K",
    location: "Pune, Maharashtra",
    eval: "Club lounge evaluation",
    duration: "4 hr · 5-star",
    tags: ["lounge", "club"],
    pay: "₹2,500",
    reimburse: "₹11,500",
    closes: "2 days",
    deadlineTime: "Feb 20, 2025, 6:00 PM",
    closesDays: 2,
    city: "Pune",
    valueScore: 87
  },
  {
    id: 6,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "Novotel Pune Nagar Road",
    chain: "Accor",
    total: "₹12K",
    location: "Pune, Maharashtra",
    eval: "Restaurant + bar evaluation",
    duration: "4 hr · 5-star",
    tags: ["restaurant", "bar", "dining"],
    pay: "₹2,000",
    reimburse: "₹10,000",
    closes: "2 days",
    deadlineTime: "Feb 20, 2025, 9:00 PM",
    closesDays: 2,
    city: "Pune",
    valueScore: 88
  },
  {
    id: 7,
    urgency: "High",
    platform: "Bare International",
    hotel: "The Westin Pune",
    chain: "Marriott",
    total: "₹16K",
    location: "Pune, Maharashtra",
    eval: "Spa + fitness center audit",
    duration: "5 hr · 5-star",
    tags: ["spa", "fitness", "wellness"],
    pay: "₹2,800",
    reimburse: "₹13,200",
    closes: "3 days",
    deadlineTime: "Feb 21, 2025, 5:00 PM",
    closesDays: 3,
    city: "Pune",
    valueScore: 90
  },
  {
    id: 8,
    urgency: "Medium",
    platform: "Shaw Hotels & Consultancy",
    hotel: "The Conrad Pune",
    chain: "Hilton",
    total: "₹28K",
    location: "Pune, Maharashtra",
    eval: "Overnight + executive lounge",
    duration: "Overnight · 5-star",
    tags: ["overnight", "lounge", "business"],
    pay: "₹4,500",
    reimburse: "₹23,500",
    closes: "4 days",
    deadlineTime: "Feb 22, 2025, 12:00 PM",
    closesDays: 4,
    city: "Pune",
    valueScore: 82
  },
  {
    id: 9,
    urgency: "High",
    platform: "HS Brands",
    hotel: "The Four Points Pune",
    chain: "Marriott",
    total: "₹13K",
    location: "Pune, Maharashtra",
    eval: "Restaurant audit + dinner",
    duration: "5 hr · 5-star",
    tags: ["restaurant", "dinner", "F&B"],
    pay: "₹2,200",
    reimburse: "₹10,800",
    closes: "3 days",
    deadlineTime: "Feb 21, 2025, 8:00 PM",
    closesDays: 3,
    city: "Pune",
    valueScore: 85
  },
  {
    id: 10,
    urgency: "Medium",
    platform: "RedQuanta",
    hotel: "Radisson Blu Pune",
    chain: "Radisson",
    total: "₹15K",
    location: "Pune, Maharashtra",
    eval: "Breakfast buffet + service",
    duration: "4 hr · 5-star",
    tags: ["breakfast", "service"],
    pay: "₹2,500",
    reimburse: "₹12,500",
    closes: "5 days",
    deadlineTime: "Feb 23, 2025, 10:00 AM",
    closesDays: 5,
    city: "Pune",
    valueScore: 78
  },
  {
    id: 11,
    urgency: "High",
    platform: "Ipsos iShopForIpsos",
    hotel: "Hyatt Pune",
    chain: "Hyatt",
    total: "₹10K",
    location: "Pune, Maharashtra",
    eval: "Lobby + concierge evaluation",
    duration: "3 hr · 5-star",
    tags: ["lobby", "concierge"],
    pay: "₹1,800",
    reimburse: "₹8,200",
    closes: "Today",
    deadlineTime: "Feb 18, 2025, 5:00 PM",
    closesDays: 0,
    city: "Pune",
    valueScore: 86
  },
  {
    id: 12,
    urgency: "Medium",
    platform: "Tophawks",
    hotel: "Courtyard Pune",
    chain: "Marriott",
    total: "₹12K",
    location: "Pune, Maharashtra",
    eval: "Meeting rooms + business center",
    duration: "4 hr · 5-star",
    tags: ["business", "meetings"],
    pay: "₹2,000",
    reimburse: "₹10,000",
    closes: "6 days",
    deadlineTime: "Feb 24, 2025, 4:00 PM",
    closesDays: 6,
    city: "Pune",
    valueScore: 75
  },
  {
    id: 13,
    urgency: "High",
    platform: "Coyle Hospitality",
    hotel: "Taj Pune",
    chain: "Taj Hotels",
    total: "₹45K",
    location: "Pune, Maharashtra",
    eval: "Two-night brand standards audit",
    duration: "Overnight · 5-star deluxe",
    tags: ["overnight", "two-night", "concierge", "luxury"],
    pay: "₹7,000",
    reimburse: "₹38,000",
    closes: "7 days",
    deadlineTime: "Feb 25, 2025, 11:00 AM",
    closesDays: 7,
    city: "Pune",
    valueScore: 100
  },
  {
    id: 14,
    urgency: "High",
    platform: "FloorWalk",
    hotel: "Fairfield by Marriott Pune",
    chain: "Marriott",
    total: "₹11K",
    location: "Pune, Maharashtra",
    eval: "Pool + recreation area",
    duration: "4 hr · 5-star",
    tags: ["pool", "recreation"],
    pay: "₹1,800",
    reimburse: "₹9,200",
    closes: "2 days",
    deadlineTime: "Feb 20, 2025, 2:00 PM",
    closesDays: 2,
    city: "Pune",
    valueScore: 83
  },
  {
    id: 15,
    urgency: "Medium",
    platform: "Bare International",
    hotel: "The Serena Pune",
    chain: "Serena Hotels",
    total: "₹20K",
    location: "Pune, Maharashtra",
    eval: "Fine dining + room service",
    duration: "Overnight · 5-star",
    tags: ["dining", "room-service", "luxury"],
    pay: "₹3,500",
    reimburse: "₹16,500",
    closes: "5 days",
    deadlineTime: "Feb 23, 2025, 12:00 PM",
    closesDays: 5,
    city: "Pune",
    valueScore: 80
  }
];

const platformUrls = {
  'FloorWalk': 'https://www.floorwalk.in/system/login.php',
  'Coyle Hospitality': 'https://coyle.shopmetrics.com/auth/index.asp#login',
  'Shaw Hotels & Consultancy': 'https://shawhotels.shopmetrics.com/auth/index.asp#login',
  'Bare International': 'https://bareinternational.shopmetrics.com/auth/index.asp#login',
  'HS Brands': 'https://sassieshop.com/2hsbrands/shoppers/LoginShopper.php',
  'RedQuanta': 'https://redquanta.shopmetrics.com/auth/index.asp#login',
  'Tophawks': 'https://tophawks.com/apply-as-mystery-shopper-top-hawks/',
  'Ipsos iShopForIpsos': 'https://www.ishopforipsos.com/en_IN/'
};

const checklistItems = [
  "Sign up at floorwalk.in/become-an-auditor with full name & valid PAN",
  "Set home city to Pune for geo-prioritised assignments",
  "Upload professional headshot — clean, well-lit, formal attire",
  "Complete demographic profile: age 28-50, income > ₹15 LPA, married/couple status",
  "Mark availability calendar 30 days ahead — never decline accepted assignments",
  "Pass FloorWalk's hotel-audit certification quiz (90% pass mark)",
  "Maintain 4.5+ rating across first 5 audits to unlock luxury tier"
];

const pipelineData = {
  Saved: [{ name: "Hyatt Regency Pune Kalyani Nagar", platform: "FloorWalk", amount: "₹11,500" }],
  Applied: [],
  Shortlisted: [],
  Completed: [],
  Paid: []
};

// For Node.js if needed, or just leave it for browser
if (typeof module !== 'undefined') {
  module.exports = { assignments, platformUrls, checklistItems, pipelineData };
}
